name = "MosekTools"
uuid = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
repo = "https://github.com/JuliaOpt/MosekTools.jl.git"
version = "0.7.4"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Mosek = "6405355b-0ac2-5fba-af84-adbd65488c0e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
MathOptInterface = "~0.8.3"
Mosek = "~0.9.11"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
